services:
  - type: web
    name: shreeji-notices
    runtime: docker
    plan: free
    envVars:
      - key: APP_PASSWORD
        value: shreeji2026
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_7nHiMWjXbue3@ep-quiet-term-a18iejjt-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
